In [14]:
import torch
print(torch.__version__)

2.8.0+cpu


In [15]:
if torch.cuda.is_available():
    print("GPU is available.")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("Gpu is not available. Using CPU")
    

Gpu is not available. Using CPU


#Creating Tensor

In [16]:
#Using empty
a =torch.empty(2 ,3)
print (a, a.dtype, a.shape)

tensor([[1.1460e-13, 1.3831e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]]) torch.float32 torch.Size([2, 3])


In [17]:
#Using Zeros
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
#Using Ones
torch.ones(4,5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [19]:
#Using rand ->random
torch.rand(2,2)

tensor([[0.4013, 0.1442],
        [0.4605, 0.4877]])

In [20]:
#Use of seed
torch.manual_seed(50)
torch.rand(2,2)


tensor([[0.6180, 0.0687],
        [0.3893, 0.0404]])

In [21]:
# Using tensor - custom tensor
torch.tensor([[1,2,3,5],[4,5,6,0]])

tensor([[1, 2, 3, 5],
        [4, 5, 6, 0]])

In [22]:
#Other ways to create tensor

#arange
print("Using arrange ->", torch.arange(0,10,2))

#Using linspace 
print("Using linspace ->", torch.linspace(0,15,3))

#Using eye
print("Using eye ->", torch.eye(5)) #create square matrix

#Using full
print("Using full ->", torch.full((2,3),5)) # all values are 5 in tensor of size 2X3

Using arrange -> tensor([0, 2, 4, 6, 8])
Using linspace -> tensor([ 0.0000,  7.5000, 15.0000])
Using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Using full -> tensor([[5, 5, 5],
        [5, 5, 5]])


#Tensor Shapes

In [23]:
x = torch.tensor([[3,1,2],[4,5,6]])
x

tensor([[3, 1, 2],
        [4, 5, 6]])

In [24]:
x.shape

torch.Size([2, 3])

In [25]:
# Same shape as x empty , ones zeros tensor
emp= torch.empty_like(x)
z = torch.zeros_like(x)
o =torch.ones_like(x)
print(f"empty tensor:\n {emp} \n zeros tensor:\n {z} \n ones tensor:\n {o}  ")

empty tensor:
 tensor([[4239837563248,             0,             0],
        [            0,             0,             0]]) 
 zeros tensor:
 tensor([[0, 0, 0],
        [0, 0, 0]]) 
 ones tensor:
 tensor([[1, 1, 1],
        [1, 1, 1]])  


 #randl_like won't work
 cause rand generate numbers between 0 to 1 which is float and x is integer

In [26]:
torch.rand_like(x)

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

In [ ]:
# Now assigning data types in rand
torch.rand_like(x, dtype= torch.float32)

tensor([[0.4013, 0.1442, 0.4605],
        [0.4877, 0.5927, 0.9634]])

#Torch Data Types

In [ ]:
# find data types
x.dtype

torch.int64

In [ ]:
# Assign data types
y = torch.tensor([1,2,3], dtype = torch.int32)
y

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
y.dtype

torch.int32

In [ ]:
# Using to()
# y was int32, let's conver to float32
y = y.to(torch.float32)
y.dtype

torch.float32

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


# **Mathematical Operations**

#1.Scalar Operation

# 

In [ ]:
torch.manual_seed(43)
a = torch.rand(2,2)
a

tensor([[0.4540, 0.1965],
        [0.9210, 0.3462]])

In [ ]:
#Addition
Addition= a+2
print(f"Addition:\n{Addition}")

#Subtraction
sub = a-2
print(f"Subtraction:\n{sub}")

#Multiplication
mul = a*2
print(f"Multiplication:\n{mul}")

#Division
div = a/2
print(f"Division:\n{div}")

#Integer Division
intdiv =a//2
print(f"Integer Division:\n{intdiv}")

#Mod
mod = a%2
print(f"Mod:\n{mod}")

#Power
pow = a**2
print(f"Power:\n{pow}")


Addition:
tensor([[2.4540, 2.1965],
        [2.9210, 2.3462]])
Subtraction:
tensor([[-1.5460, -1.8035],
        [-1.0790, -1.6538]])
Multiplication:
tensor([[0.9079, 0.3930],
        [1.8421, 0.6924]])
Division:
tensor([[0.2270, 0.0982],
        [0.4605, 0.1731]])
Integer Division:
tensor([[0., 0.],
        [0., 0.]])
Mod:
tensor([[0.4540, 0.1965],
        [0.9210, 0.3462]])
Power:
tensor([[0.2061, 0.0386],
        [0.8483, 0.1198]])


#2.Element wise Operation

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)
print(f"M tensor:\n{m}\n N tensor:\n {n}")

M tensor:
tensor([[0.4275, 0.2761, 0.8396],
        [0.1563, 0.1072, 0.7261]])
 N tensor:
 tensor([[0.3241, 0.8892, 0.1318],
        [0.8375, 0.5625, 0.4138]])


In [ ]:
#add
add1 =m+n
print(f"Addition of M and N:\n {add1}")
print("\n")
#sub
sub1 = m-n
print(f"Subtraction of M and N:\n {sub1}")

#Multiply
mul1 = m*n
print(f"Multiplication of M and N:\n {mul1}")
print("\n")

#Divide
div1 = m/n
print(f"Division of M and N:\n {div1}")
print("\n")

#mod
mod1 = m%n
print(f"Mod of M and N:\n {mod1}")

Addition of M and N:
 tensor([[0.7516, 1.1654, 0.9714],
        [0.9937, 0.6697, 1.1400]])


Subtraction of M and N:
 tensor([[ 0.1035, -0.6131,  0.7078],
        [-0.6812, -0.4553,  0.3123]])
Multiplication of M and N:
 tensor([[0.1385, 0.2455, 0.1107],
        [0.1309, 0.0603, 0.3005]])


Division of M and N:
 tensor([[1.3193, 0.3105, 6.3696],
        [0.1866, 0.1906, 1.7547]])


Mod of M and N:
 tensor([[0.1035, 0.2761, 0.0487],
        [0.1563, 0.1072, 0.3123]])


#Element wise operation on single tensor

In [ ]:
c =torch.tensor([1,2,3,-8,9,-6])

In [ ]:
#absolute
abs1= torch.abs(c)
print(f"Absolute value of c tensor:\n {abs1}")
print("\n")

#Negative
neg1 = torch.neg(c)
print(f"Negative value of c tensor:\n {neg1}")

Absolute value of c tensor:
 tensor([1, 2, 3, 8, 9, 6])


Negative value of c tensor:
 tensor([-1, -2, -3,  8, -9,  6])


In [31]:
d = torch.tensor([1.2,3.2,5.1,4.4])

In [32]:
#round #closest round value
round1 = torch.round(d)
print(f"Round value of d tensor:\n {round1}")
print("\n")

#ceil #roundup upper value
ceil1 = torch.ceil(d)
print(f"Ceil value of d tensor:\n {ceil1}")
print("\n")

#floor #rounddown lower value
floor1 = torch.floor(d)
print(f"Floor value of d tensor:\n {floor1}")
print("\n")

#clamp #limit values within a range
clamp1 = torch.clamp(d, min=3, max = 4)
print(f"Clamp value of d tensor:\n {clamp1}")

Round value of d tensor:
 tensor([1., 3., 5., 4.])


Ceil value of d tensor:
 tensor([2., 4., 6., 5.])


Floor value of d tensor:
 tensor([1., 3., 5., 4.])


Clamp value of d tensor:
 tensor([3.0000, 3.2000, 4.0000, 4.0000])


#3.Reduction Operation

In [43]:
e = torch.randint(size=(2,3), low=3 , high =10,dtype=torch.float32)
e

tensor([[5., 3., 7.],
        [5., 5., 6.]])

In [44]:
#sum
sum1 = torch.sum(e)
#print(f"Sum of all elements in e tensor:\n {sum1}")
print("\n")
sum1
#sum along columns
colsum = torch.sum(e , dim=0)
print(f"Sum of elements along columns in e tensor:\n {colsum}")
print("\n")

#sum along rows
rowsum = torch.sum(e, dim=1)
print(f"Sum of elements along rows in e tensor:\n {rowsum}")



Sum of elements along columns in e tensor:
 tensor([10.,  8., 13.])


Sum of elements along rows in e tensor:
 tensor([15., 16.])


In [45]:
sum1

tensor(31.)

In [48]:
#mean
mean1 = torch.mean(e)
print(f"Mean of all elements in e tensor:\n {mean1}")
print("\n")

#mean along columns
colmean = torch.mean(e, dim=0)
print(f"Mean of elements along columns in e tensor:\n {colmean}")
print("\n")

#mean along rows
rowmean = torch.mean(e, dim=1)
print(f"Mean of elements along rows in e tensor:\n {rowmean}")


Mean of all elements in e tensor:
 5.166666507720947


Mean of elements along columns in e tensor:
 tensor([5.0000, 4.0000, 6.5000])


Mean of elements along rows in e tensor:
 tensor([5.0000, 5.3333])


In [52]:
#median
med1 = torch.median(e)
med1


tensor(5.)

In [54]:
# max
max1 = torch.max(e)
print(f"Max value in e tensor:\n {max1}")
print("\n")

#min
min1 = torch.min(e)
print(f"Min value in e tensor:\n {min1}")
print("\n")

#priduct
prod1 = torch.prod(e)
print(f"Product of all elements in e tensor:\n {prod1}")
print("\n")

#Standard Deviation
std1 = torch.std(e)
print(f"Standard Deviation of all elements in e tensor:\n {std1}")

Max value in e tensor:
 7.0


Min value in e tensor:
 3.0


Product of all elements in e tensor:
 15750.0


Standard Deviation of all elements in e tensor:
 1.3291600942611694


In [55]:
#Argmax  
#Position of max value in tensor
argmax1 = torch.argmax(e)
print(f"Position of max value in e tensor:\n {argmax1}")
print("\n")

#Argmin
#Position of min value in tensor
argmin1 = torch.argmin(e)
print(f"Position of min value in e tensor:\n {argmin1}")

Position of max value in e tensor:
 2


Position of min value in e tensor:
 1


 #4.Matrix Operations

In [56]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[9, 9, 1],
        [8, 3, 4]])
tensor([[2, 1],
        [4, 3],
        [8, 3]])


In [57]:
# matrix multiplication
multi_mat = torch.matmul(f,g) # Another way is f @ g
print(f"Matrix multiplication of f and g:\n {multi_mat}")

Matrix multiplication of f and g:
 tensor([[62, 39],
        [60, 29]])


In [58]:
f@g

tensor([[62, 39],
        [60, 29]])

In [60]:
vector1 = torch.tensor([1,2,3])
vector2 = torch.tensor([4,5,6])

In [61]:
#dot product
dot1 = torch.dot(vector1 , vector2)
dot1

tensor(32)

In [63]:
f

tensor([[9, 9, 1],
        [8, 3, 4]])

In [ ]:
#transpose

torch.transpose(f,0,1) 

# torch.transpose(matrix_name , first_dimension to be swapped , second_dimension to be swapped )

tensor([[9, 8],
        [9, 3],
        [1, 4]])

In [64]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[0., 1., 5.],
        [9., 8., 4.],
        [9., 4., 2.]])

In [65]:
#Determinant
torch.det(h)

tensor(-162.0000)

In [67]:
#Inverse
torch.inverse(h)


tensor([[-8.2784e-10, -1.1111e-01,  2.2222e-01],
        [-1.1111e-01,  2.7778e-01, -2.7778e-01],
        [ 2.2222e-01, -5.5556e-02,  5.5556e-02]])

#5.Comparison

In [68]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[8, 7, 0],
        [6, 2, 2]])
tensor([[1, 8, 3],
        [1, 6, 4]])


In [71]:
#Greater Than
i>j

tensor([[ True, False, False],
        [ True, False, False]])

In [72]:
#less than
i<j

tensor([[False,  True,  True],
        [False,  True,  True]])

In [73]:
# equal to
i==j

tensor([[False, False, False],
        [False, False, False]])

In [74]:
# not equal to
i!=j

tensor([[True, True, True],
        [True, True, True]])

In [75]:
#Greater than equal to
i>=j

tensor([[ True, False, False],
        [ True, False, False]])

In [76]:
#less than equal to 
i<=j

tensor([[False,  True,  True],
        [False,  True,  True]])

#6.Special function

In [79]:
k = torch.randint(size=(2,3), low=2, high=10, dtype=torch.float32)
k

tensor([[2., 5., 8.],
        [8., 7., 9.]])

In [83]:
#log
log1 = torch.log(k)
print(f"Logarithm of k tensor:\n {log1}")
print("\n")

# EXP
exp1 = torch.exp(k)
print(f"Exponential of k tensor:\n {exp1}")
print("\n")

#Square Root
sqrt1 = torch.sqrt(k)
print(f"Square Root of k tensor:\n {sqrt1}")
print("\n")

#Softmax
softmax1 = torch.softmax(k,dim=0)
print(f"Softmax of k tensor along dim 0:\n {softmax1}")
print("\n")

#relu
relu1 = torch.relu(k)
print(f"ReLU of k tensor:\n {relu1}")


Logarithm of k tensor:
 tensor([[0.6931, 1.6094, 2.0794],
        [2.0794, 1.9459, 2.1972]])


Exponential of k tensor:
 tensor([[7.3891e+00, 1.4841e+02, 2.9810e+03],
        [2.9810e+03, 1.0966e+03, 8.1031e+03]])


Square Root of k tensor:
 tensor([[1.4142, 2.2361, 2.8284],
        [2.8284, 2.6458, 3.0000]])


Softmax of k tensor along dim 0:
 tensor([[0.0025, 0.1192, 0.2689],
        [0.9975, 0.8808, 0.7311]])


ReLU of k tensor:
 tensor([[2., 5., 8.],
        [8., 7., 9.]])


# Inplace Operation

In [91]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6065, 0.5926, 0.7300],
        [0.9768, 0.9680, 0.1494]])
tensor([[0.9826, 0.7921, 0.5842],
        [0.9628, 0.3192, 0.5750]])


In addition m+n create a new tensor to store the addition
But with inplace addition in store in the previous tensor

In [92]:
m.add_(n)

tensor([[1.5891, 1.3846, 1.3141],
        [1.9396, 1.2873, 0.7244]])

In [93]:
m
#here see m is same as the addition result of m and n

tensor([[1.5891, 1.3846, 1.3141],
        [1.9396, 1.2873, 0.7244]])

In [94]:
n

tensor([[0.9826, 0.7921, 0.5842],
        [0.9628, 0.3192, 0.5750]])

In [99]:
torch.relu(m)

tensor([[1.5891, 1.3846, 1.3141],
        [1.9396, 1.2873, 0.7244]])

In [100]:
# inplace relu
m.relu_()

tensor([[1.5891, 1.3846, 1.3141],
        [1.9396, 1.2873, 0.7244]])

In [101]:
m

tensor([[1.5891, 1.3846, 1.3141],
        [1.9396, 1.2873, 0.7244]])

# Copying Tensor

In [102]:
v = torch.randint(size=(2,3), low=2, high=10)
v

tensor([[6, 8, 3],
        [6, 6, 6]])

In [105]:
b = v
b

tensor([[6, 8, 3],
        [6, 6, 6]])

In [107]:
v [0][0] = 0
v

tensor([[0, 8, 3],
        [6, 6, 6]])

In [109]:
b 
# b changed as well which is not desirable because they share same memory location

print(f" id of v:{id(v)} \n id of b:{id(b)}")

 id of v:1387346373648 
 id of b:1387346373648


In [111]:
# So do clone to avoid this issue
s = v.clone()
s

tensor([[0, 8, 3],
        [6, 6, 6]])

In [112]:
v[0][0] = 9
v

tensor([[9, 8, 3],
        [6, 6, 6]])

In [113]:
s

tensor([[0, 8, 3],
        [6, 6, 6]])

In [114]:
print(f" id of v:{id(v)} \n id of s:{id(s)}")

 id of v:1387346373648 
 id of s:1387347054656


# GPU Operation

In [115]:
device = torch.device("cuda")

In [ ]:
# creating tensor on GPU
t = torch.rand(2,3, device=device)

In [ ]:
#Moving existing tensoor to gpu
s.to(device)

# Reshaping

In [117]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [119]:
#Reshape
a.reshape(2,2,4)


tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [120]:
#flatten 
# Make it 1D tensor
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [121]:
b = torch.rand(1,3,4)
b

tensor([[[0.1921, 0.7686, 0.2524, 0.3668],
         [0.0484, 0.7829, 0.7032, 0.7265],
         [0.5794, 0.1412, 0.8105, 0.9284]]])

In [125]:
#Permute 
#Permutation of dimensions
#basically change the order of dimensions
b.permute(2,0,1).shape

torch.Size([4, 1, 3])

In [130]:
#Unsqueeze
# Basically adding extra dimension
c= torch.rand(2,2,3)
d=c.unsqueeze(0)
d
#c.unsqueeze(dimension position to add)

tensor([[[[0.2781, 0.0516, 0.3258],
          [0.4643, 0.1953, 0.6413]],

         [[0.0191, 0.4625, 0.7201],
          [0.1136, 0.2195, 0.1274]]]])

In [131]:
d.shape

torch.Size([1, 2, 2, 3])

In [133]:
# Squeeze
# Basically removing dimensions of size 1
e = d.squeeze()
e

tensor([[[0.2781, 0.0516, 0.3258],
         [0.4643, 0.1953, 0.6413]],

        [[0.0191, 0.4625, 0.7201],
         [0.1136, 0.2195, 0.1274]]])

In [134]:
e.shape

torch.Size([2, 2, 3])

# Numpy Pytorch exchange

In [137]:
import numpy as np
np_array = np.array([[1,2,3],[4,5,6]])
np_array


array([[1, 2, 3],
       [4, 5, 6]])

In [138]:
#Numpy to Pytorch tensor
torch_tensor1 = torch.from_numpy(np_array)
torch_tensor1

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [143]:
type(torch_tensor1)

torch.Tensor

In [140]:
d = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.int32)
d

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [141]:
# Tensor to Numpy
d_numpy = d.numpy()
d_numpy

array([[1, 2, 3],
       [4, 5, 6]])

In [142]:
type(d_numpy)

numpy.ndarray