#Import Library


In [8]:
import numpy as np
import pandas as pd
import torch

In [9]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()


id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [10]:
#Downloading the dataset to device
df.to_csv('data.csv', index=False)

In [11]:
df.shape

(569, 33)

In [12]:
# deleting the 'id' column  and Unnamed: 32 column
df.drop(columns=['id', 'Unnamed: 32'], inplace =True)

In [13]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [14]:
df.shape

(569, 31)

In [15]:
x = df.iloc[:, 1:]
y = df.iloc[:, 0]

In [16]:
x.head()

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   fractal_dimension_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [17]:
y.head()

0    M
1    M
2    M
3    M
4    M
Name: diagnosis, dtype: object

#Test train Split

In [18]:
from sklearn.model_selection import train_test_split
x_train, x_test ,y_train, y_test = train_test_split(x,y, test_size=0.2)

#Scalling

In [19]:
from sklearn.preprocessing import StandardScaler
scaler =StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [20]:
x_train

array([[-1.71413046, -0.57264588, -1.687868  , ..., -1.35482518,
         0.31153756, -0.54352339],
       [-0.21885214,  0.50218647, -0.2623523 , ..., -0.06637178,
         0.13832967, -0.68325258],
       [-1.59978901, -0.17355201, -1.58944249, ..., -1.74093955,
         0.36927352, -0.16790156],
       ...,
       [ 0.3685379 ,  0.38880753,  0.4291076 , ...,  1.47266443,
         0.15237355,  1.08806732],
       [-0.61234644, -0.10552464, -0.65605434, ..., -0.97398148,
        -0.03955951, -0.18543412],
       [ 0.44837732, -0.3345501 ,  0.45805628, ...,  0.9847508 ,
         1.38355392,  1.08806732]])

In [21]:
y_train

46     B
40     M
314    B
531    B
7      M
      ..
229    M
359    B
417    M
346    B
11     M
Name: diagnosis, Length: 455, dtype: object

#Label Encoding y train , y test

In [22]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [23]:
y_train

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,

#Numpy array to tensor

In [24]:
import torch
x_train_tensor  = torch.from_numpy(x_train)
x_test_tensor   = torch.from_numpy(x_test)
y_train_tensor  = torch.from_numpy(y_train)
y_test_tensor   = torch.from_numpy(y_test)  

In [25]:
x_train_tensor.shape

torch.Size([455, 30])

In [26]:
x_test_tensor.shape

torch.Size([114, 30])

In [27]:
y_train_tensor.shape

torch.Size([455])

In [28]:
y_test_tensor.shape

torch.Size([114])

# Defining Model

In [ ]:
class MySimpleNN():
#x.shape[1] ,1 gives number of features cause it's first row
#bias starts with zero

    def __init__(self,x):
        self.weights = torch.rand(x.shape[1],1, dtype = torch.float64 , requires_grad=True)
        self.bias = torch.zeros(1 , dtype = torch.float64 ,requires_grad =True)

    def forward(self,x):
            z = torch.matmul(x ,self.weights) + self.bias
            y_pred = torch.sigmoid(z)
            return y_pred
        
    def loss_function(self,y_pred,y):
            #Clamp prediction to avoid log(0) error
            epsilon = 1e-7
            y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
            
            #Calculate loss
            loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
            return loss
        


#Important Parameters

In [40]:
learning_rate =0.1
epochs =25

#Training Pipeline

      Create model -> Define loop -> Forward Pass -> Loss calculation -> Backward Pass -> Parameters Update -> Zero grad (so that start from zero) -> Print loss in each epochs

In [41]:
#Create model
model = MySimpleNN(x_train_tensor)

#define loop
for epoch in range(epochs):

    #Forward pass
    y_pred = model.forward(x_train_tensor)

    #Loss calculation
    loss = model.loss_function(y_pred, y_train_tensor)


    # Backward Pass
    loss.backward()

    #Parameters Update ( weights and bias)
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad
    
    #Zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    #Print loss in each epochs
    print(f'Epoch {epoch+1}/{epochs}, Loss: {loss.item():.4f}') 


Epoch 1/25, Loss: 4.0532
Epoch 2/25, Loss: 3.9389
Epoch 3/25, Loss: 3.8190
Epoch 4/25, Loss: 3.6944
Epoch 5/25, Loss: 3.5650
Epoch 6/25, Loss: 3.4296
Epoch 7/25, Loss: 3.2912
Epoch 8/25, Loss: 3.1495
Epoch 9/25, Loss: 3.0024
Epoch 10/25, Loss: 2.8516
Epoch 11/25, Loss: 2.6953
Epoch 12/25, Loss: 2.5361
Epoch 13/25, Loss: 2.3772
Epoch 14/25, Loss: 2.2136
Epoch 15/25, Loss: 2.0529
Epoch 16/25, Loss: 1.8950
Epoch 17/25, Loss: 1.7403
Epoch 18/25, Loss: 1.5882
Epoch 19/25, Loss: 1.4439
Epoch 20/25, Loss: 1.3137
Epoch 21/25, Loss: 1.1989
Epoch 22/25, Loss: 1.1007
Epoch 23/25, Loss: 1.0194
Epoch 24/25, Loss: 0.9544
Epoch 25/25, Loss: 0.9041


#Evaluation

In [45]:
#Model evaluation
with torch.no_grad():
    y_pred = model.forward(x_test_tensor)
    y_pred = (y_pred >= 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5387811660766602


In [46]:
print(y_pred)

tensor([[1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
      